name: Build, Test and Publish the Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Build the package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install twine
        python -m pip install .
        python setup.py sdist

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:

      - uses: actions/checkout@v3

      - name: Run PyTests
        run: |
          python -m pip install -r requirements.txt
          python -m pytest


  upload:
    runs-on: ubuntu-latest

    needs: test

    steps:

      - uses: actions/checkout@v3

      - name: Publish Package

        env:
          PYPI_TOKEN: ${{ secrets.PYPI_SECRET }}

        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install twine
          python -m pip install .
          python setup.py sdist
          python -m twine check dist/*
          python -m twine upload --verbose --skip-existing dist/* -u __token__ -p $PYPI_TOKEN
